<ul>
<li>Version 2.0.3 - 1 August 2017
	<ul>
	<li>Minor bug fixed</li>
	</ul>
</li>
<li>Version 2.0.2 - 3 April 2017
	<ul>
	<li>Bug #11351: fixed - Warning: Creating default object from empty value</li>
	</ul>
</li>
<li>Version 2.0.1 - 14 October 2015
	<ul>
	<li>fix for add/edit/reset template</li>
	<li>Fix for error: Parameter 2 to SmartyBC::assign_by_ref() expected to be a reference</li>
	<li>Bug #10055: fixed - Category #1 can't be deleted</li>
	<li>Bug #10414: fixed - Reindex in Search module gives SQL error</li>
	<li>Bug #10620: fixed - Notices related to Smarty scope in list template</li>
	<li>Bug #10639: fixed - Error re-indexing search module</li>
	</ul>
</li>
<li>Version 2.0 - 21 May 2014
	<ul>
	<li>Changes to make module CMSms 2.0 compatible</li>
	<li>Minimum required CMSms version set to 1.11</li>
    <li>Bug #9893: fixed - Unable to add entries for any category except general in admin backend</li>
    <li>Bug #9925: fixed - Custom Modulename won't save</li>
    <li>Bug #9931: fixed - Unable to edit Entries in different Categories</li>
	</ul>
</li>
<li>Version 1.0.1 - 9 December 2013
	<ul>
	<li>Minor bugfix</li>
	</ul>
</li>
<li>Version 1.0 - 9 May 2013
	<ul>
	<li>Parse smarty tags in question and answer fields</li>
	<li>Fix csv import</li>
	</ul>
</li>
<li>Version 0.2 - 6 May 2013
	<ul>
	<li>Initial Release</li>
	</ul>
</li>
</ul>
