<ul>
	<li><b>Version 1.5.3</b> (2017-12-27)<br />
		- Updated CGCalendar tag from "list" to "upcominglist".<br />
		- Improved http request for sitemap renewal, fix for servers with <i>allow_url_fopen = 0</i>.<br />
		- Admin template changes.</li>
	<li><b>Version 1.5.2</b> (2017-10-23)<br />
		- Code clean up.<br />
		- Improvements to module installation.<br />
		- Improvements to update sitemap task.</li>
	<li><b>Version 1.5.1</b> (2017-08-11)<br />
		- Fix to module installation.</li>
	<li><b>Version 1.5</b> (2017-08-08)<br />
		- Important improvements to the sitemap creation method.<br />
		- Short module tags are now allowed.</li>
	<li><b>Version 1.4</b> (2017-07-20)<br />
		- Sort sitemap tabs and sitemap index file.<br />
		- Update sitemaps every 24 hours.<br />
		- Added check if module is installed before saving new sitemap.<br />
		- Added check for double name when saving an existing sitemap.</li>
	<li><b>Version 1.3.1</b> (2017-07-03)<br />
		- Switch back from https to http protocol in sitemap templates for now. <i>Google, please make up your mind</i> :-/</li>
	<li><b>Version 1.3</b> (2017-06-24)<br />
		- Module added to the Translation Center.<br />
		- Added "Permissive Smarty" warning to the main module page.</li>
	<li><b>Version 1.2.1</b> (2017-06-09)<br />
		- Update CGBlog Smarty tag.<br />
		- Add "Permissive Smarty" requirement to help text.</li>
	<li><b>Version 1.2</b> (2017-05-27)<br />
		- Add sitemap templates for CGCalendar, Company Directory and LISE instances.<br />
		- Start to add documentation<br />
		- Added default template content to the sitemap page for modules that are not yet Design Manager compatible.</li>
	<li><b>Version 1.1</b> (2017-05-20)<br />
		- Set correct file headers. Sitemap index file is recreated on upgrade. Others will be recreated within 12 hours...<br />
		- Change default templates urlset to https. For upgrades you can/need to change this yourself in the templates in Design Manager.<br />
		- Fix regex sitemap name.<br />
		- Display file url beside the open file button in the Admin tabs.<br />
		- Improve help text.</li>
	<li><b>Version 1.0</b> (2017-05-10)<br />
		Initial release</li>
</ul>