<ul>
  <li>1.1 - September, 2007 <em>(rcampbell@skinnyfishmedia.com)</em>
    <ul>
      <li>Added support for pretty urls</li>
      <li>Filled out the help</li>
      <li>Added a category list mode</li>
      <li>Added support for frontend editing of companies</li>
      <li>Added support for public and admin only fields in companies</li>
      <li>Added different sorting capabilities in summary view</li>
      <li>Changed Minimum CMS Version and added support for the 1.1 series</li>
    </ul>
  </li>
  <li>1.1.1 - November, 2007 <em>(rcampbell@skinnyfishmedia.com)</em>
    <ul>
      <li>Fixed a problem with the detail links in summary mode when pretty urls were disabled.</li>
    </ul>
  </li>
  <li>1.1.2 - November, 2007 <em>(rcampbell@skinnyfishmedia.com)</em>
    <ul>
      <li>Now use cms_move_uploaded_file instead of move_uploaded_file</li>
      <li>Require CMS 1.2.1 or later</li>
    </ul>
  </li>
  <li>1.1.3 - February, 2008 <em>(rcampbell@skinnyfishmedia.com)</em>
    <ul>
      <li>Adds pagination to summary view</li>
      <li>Fixes a problem with pretty urls in summary view</li>
      <li>Fixes a problem with the sort order preferences</li>
      <li>(_SjG) - Implements tsw\'s patch for custom fields in the summary template</li>
    </ul>
  </li>
  <li>1.1.4 - June, 2008 <em>(calguy1000@cmsmadesimple.org)</em>
    <ul>
      <li>Fix to the tabs</li>
      <li>Minor fix to the status field when editing a company.</li>
      <li>Minor fix to the checkbox custom fields when editing a company.</li>
      <li>Fix to CSV Export.</li>
      <li>Fix to the preferences tab.</li>
    </ul>
  </li>
  <li>1.1.5 - June, 2008 <em>(calguy1000@cmsmadesimple.org)</em>
    <ul>
      <li>Fix a minor issue with preferences</li>
      <li>Fix some queries that were not using cms_db_prefix</li>
    </ul>
  </li>
  <li>1.1.6 - July, 2008 <em>(calguy1000@cmsmadesimple.org)</em>
    <ul>
      <li>Add the showall parameter to the categorylist action.</li>
      <li>Split out a couple of more files.</li>
    </ul>
  </li>
  <li>1.1.7 - February, 2009 <em>(calguy1000@cmsmadesimple.org)</em>
    <ul>
      <li>Fixed delete company stuff.</li>
    </ul>
  </li>
  <li>1.1.8 - April, 2009 <em>(calguy1000@cmsmadesimple.org)</em>
    <ul>
      <li>Add More Indexes.</li>
    </ul>
  </li>
  <li>1.2 - May, 2009 <em>(calguy1000@cmsmadesimple.org)</em>
    <ul>
      <li>Added latitude and longitude fields.</li>
      <li>Added capability to lookup lattitude and longitude if CGGoogleMap is installed.</li>
      <li>Added search functionality, with zipcode lookup (requires the postcode module).</li>
      <li>Added export to csv functionality.</li>
      <li>Rewrite import from csv functionality.</li>
    </ul>
  </li>
  <li>1.3 - July, 2009 <em>(calguy1000@hotmail.com)</em>
    <ul>
      <li>Added support for pretty urls</li>
      <li>Filled out the help</li>
      <li>Added a category list mode</li>
      <li>Added support for frontend editing of companies</li>
      <li>Added support for public and admin only fields in companies</li>
      <li>Added different sorting capabilities in summary view</li>
      <li>Changed Minimum CMS Version and added support for the 1.1 series</li>
    </ul>
  </li>
  <li>1.3.2 - August, 2009 <em>(calguy1000@hotmail.com)</em>
    <ul>
      <li>Fix minor error in the installer.</li>
      <li>In summary mode, ensure that a company is only output once.</li>
    </ul>
  </li>
  <li>1.3.3 - August, 2009 <em>(calguy1000@hotmail.com)</em>
    <ul>
      <li>Fix errors with entities in frontend wysiwygs.</li>
      <li>Fix error in bounding box calculation.</li>
      <li>Numerous other small bug fixes.</li>
    </ul>
  </li>
  <li>1.3.4 - September, 2009 <em>(calguy1000@hotmail.com)</em>
    <ul>
      <li>Fix some more small issues with frontend submit</li>
    </ul>
  </li>
  <li>1.4 - Oct, 2009 <em>(calguy1000@cmsmadesimple.org)</em>
    <ul>
     <li>Added KML Import</li>
     <li>Minor bug fixes.</li>
    </ul>
  </li>
  <li>1.4.1 - October, 2009 <em>(calguy1000@hotmail.com)</em>
    <ul>
      <li>Adds ability to import fields from KML.</li>
      <li>Adds field type to the output for custom fields.</li>
    </ul>
  </li>
  <li>1.5 - January, 2010
    <ul>
      <li>Adds the ability for frontend users to add/edit/delete their own company listings.</li>
    </ul>
  </li>
  <li>1.5.1 - January, 2010
    <ul>
      <li>Adds the ability to browse by hierarchy.</li>
    </ul>
  </li>
  <li>1.5.2 - January, 2010
    <ul>
      <li>Rewrite of CSV import stuff.</li>
      <li>Adds frontend importing from csv.</li>
      <li>Adds frontend delete action.</li>
    </ul>
  </li>
  <li>1.5.3 - March, 2010
    <ul>
      <li>Improvements to search.</li>
      <li>Minor bug fixes.</li>
    </ul>
  </li>
  <li>1.5.4 - May, 2010
    <ul>
      <li>Adds sorting by public custom fields.</li>
    </ul>
  </li>
  <li>1.5.5 - May, 2010
    <ul>
      <li>Minor bug fixes.</li>
    </ul>
  </li>
  <li>1.5.7 - May, 2010
    <ul>
      <li>Minor bug fixes.</li>
    </ul>
  </li>
  <li>1.5.8 - May, 2010
    <ul>
      <li>Adds category information for each matching product in summary view.</li>
    </ul>
  </li>
  <li>1.6 - June, 2010
    <ul>
      <li>Fixes a minor issue with the search function (copy/paste error)</li>
      <li>Adds company name information to the detail url.</li>
      <li>Adds &quot;back&quot; link to the settings and template pages.</li>
      <li>Adds functionality to allow duplicating a company record.</li>
    </ul>
  </li>
  <li>1.6.1 - June, 2010
    <ul>
      <li>Adds extra fields to categories.</li>
    </ul>
  </li>
  <li>1.6.2 - July, 2010
    <ul>
      <li>Minor bug fixes.</li>
    </ul>
  </li>
  <li>1.6.3 - July, 2010
    <ul>
      <li>Minor bug fixes.</li>
    </ul>
  </li>
  <li>1.6.4 - July, 2010
    <ul>
      <li>Sort field definitions by name.</li>
      <li>Adds category specific extra1,extra2,extra3 fields associated with Companies.</li>
    </ul>
  </li>
  <li>1.6.5 - August, 2010
    <ul>
      <li>Adds id option to sortby.</li>
    </ul>
  </li>
  <li>1.6.7 - August, 2010
    <ul>
      <li>Adds integer sorting by the sortby=f:field_name stuff.</li>
      <li>Minor improvement to the search stuff wrt categories.</li>
      <li>Sort the categories output to the search form.</li>
    </ul>
  </li>
  <li>1.6.8 - September, 2010
    <ul>
      <li>Fixes to search action.</li>
    </ul>
  </li>
  <li>1.6.9 - September, 2010
    <ul>
      <li>CSV Import Improvements.</li>
    </ul>
  </li>
  <li>1.7 - September, 2010
    <ul>
      <li>Adds hierarchy capabilities to search action.</li>
    </ul>
  </li>
  <li>1.7.2 - September, 2010
    <ul>
      <li>Adds the ability to do a LIKE search on the address field when doing a postcode search.</li>
    </ul>
  </li>
  <li>1.7.3 - January, 2011
   <ul>
     <li>Many minor bug fixes, including changes to work with new CGGM</li>
   </ul>
  </li>
  <li>1.8 - January, 2011
   <ul>
   <li>Adds support for company URLS (ala CMSMS 1.9) when companies are updated from the admin interface.</li>
   <li>Adds support for doing a 301 redirect to the new URL if a company is accessed via the old URL and a new URL exists.</li>
   <li>Adds the ability to pass the latitude and longitude in to the search.</li>
   </ul>
  </li>
  <li>1.8.1 - March, 2011
   <ul>
   <li>Bug fixes.</li>
   </ul>
  </li>
  <li>1.8.2 - March, 2011
   <ul>
   <li>Adds $entry->fields to the detail and summary views.</li>
   <li>Officially deprecate the customfieldsbyname stuff.</li>
   <li>Add $entry->canonical to the detail view.</li>
   </ul>
  </li>
  <li>1.9 - August, 2011
   <ul>
   <li>Adds the ability to update company records via csv files.</li>
   </ul>
  </li>
  <li>1.10 - September, 2011
   <ul>
   <li>Adds new filter, query, and pagination classes.</li>
   <li>Adds the ability to preload field and category information for selected companies.</li>
   <li>Rewrite summary view to use new classes.</li>
   <li>Removes the category form from the summary view... many better ways to handle this.</li>
   </ul>
  </li>
  <li>1.10.1 - September, 2011
   <ul>
   <li>Minor bug fixes.</li>
   </ul>
  </li>
  <li>1.10.10 - November, 2011
   <ul>
   <li>Fixes an issue with image upload fields when editing companies.</li>
   </ul>
  </li>
  <li>1.10.11 - November, 2011
   <ul>
     <li>Category names must now only have valid chars.</li>
     <li>Minor fixes.</li>
   </ul>
  <li>
  <li>1.11 - December, 2011
   <ul>
     <li>Minor bug fixes.</li>
     <li>Improvements to the detail view (some templates may need changing).</li>
   </ul>
  </li>
  <li>1.12 - December, 2011
   <ul>
     <li>Minor bug fixes.</li>
     <li>Adds filtering to the company list in the admin interface.</li>
     <li>Adds the category2 and category3 parameters.</li>
     <li>Adds the ability to specify a category OR a hier parameter to the categorylist view.</li>
   </ul>
  </li>
 <li>1.13 - January, 2012
   <ul>
     <li>Adds file field type.</li>
     <li>Fixes problem with logo and picture files being deleted.</li>
   </ul>
 </li>
 <li>1.13.1 - March, 2012
   <ul>
    <li>Numerous minor bug fixes.</li>
   </ul>
 </li>
 <li>1.13.2 - April, 2012
   <ul>
    <li>More audit lines.</li>
   </ul>
 </li>
 <li>1.14 - May, 2012
   <ul>
   <li>Improvements to the cd_company class.</li>
   <li>Add company (admin) is now getting more oopified.</li>
   <li>Edit company (admin) is now getting more oopified.</li>
   <li>Minor fix to the hierarchy tab.</li>
   <li>New Events (OnAddCompany, OnEditCompany, OnDeleteCompany) -- in progress</li>
   <li>Extra fields are now added to the search terms (text and textarea fields only). -- in progress</li>
   <li>Search re-index now oopified and faster.</li>
   <li>Frontend editing completely rewritten
      <ul>
        <li>Use the new action (there is an option in the admin panel)</li>
        <li>Supports editing custom fields (public only).</li>
        <li>Supports file uploads, image processing ala CGExtensions</li>
        <li>Enhanced security.</li>
        <li>Default template includes lookup functionality (if CGGM is available)</li>
        <li>Searchable.</li>
      </ul>
      </li>
   <li>Fixes to KML Import.</li>
   <li>Adds the hierarchy info to the summary and detail views.</li>
   <li>Adds radius searching capabilities, and sorting by distance.</li>
   <li>Adds regexp search for name parameter.</li>
   <li>Fixes a bug in CSV import wrt lat/long values.</li>
   </ul>
 </li>
 <li>1.14.1 - June, 2012
   <ul>
   <li>Edit Company (admin side) Fixes.</li>
   <li>Compay Company Fixes.</li>
   <li>Moved help out of lang file.</li>
   </ul>
 </li>
 <li>1.14.2 - June, 2012
   <ul>
   <li>Fixes issue with draft status.</li>
   <li>fixes issue with cd_company_query, status, and frontend views.</li>
   </ul>
 </li>
 <li>1.14.3 - July, 2012
   <ul>
   <li>Categories are now output in ascending order by name, everywhere.</li>
   <li>More functions in cd_utils.</li>
   <li>Minor bugfix to accepting html in the detail view.</li>
   </ul>
 </li>
 <li>1.14.4 - July, 2012
   <ul>
   <li>Bugfix: Set owner id to -1 for imported items.</li>
   </ul>
 </ii>
 <li>1.15.x
   <ul>
   <li>Begin work on new search action.</li>
   <li>Minor bug fixes.</li>
   <li>Adds ability to output company searches as an array.</li>
   </ul>
 </li>
 <li>1.16.x
   <ul>
   <li>Add the {cd_getcompany} tag.</li>
   <li>Fixes a bunch of minor bugs.</li>
   <li>Only clean values in cd_company for admin requests... see how that works out.</li>
   <li>CSV import improvements.<lli>
   </ul>
 </li>
 <li>1.17.x
   <ul>
   <li>Rationalization of admin interface tabs.</li>
   <li>Minor optimzations.</li>
   <li>Adds support for the album field type including for frontend editing.
     <p>The album field type allows associating multiple images with a single company entry.  They are represented in the summary and detail templates as a simple array of filenames.  You may build your own display mechanism from this.</p>
     <p>The album field type does not provide any image processing capabilities.  Image processing such as watermarking or thumbnailing can be done at the tiem of display with an addon module like CGSmartImage.</p>
     <p><strong>Note:</strong> In order to see the album field types you will need to create a new &quot;Frontend Edit Company&quot; template from defaults (after restoring the default template to factory defaults in the default templates tab.</p>
     <p>Additionally you will need to create new frontend album templates.</p>
   </li>
   </ul>
 </li>
 <li>1.18.x
   <ul>
     <li>Modifies the cd_company_filter and cd_company_query classes to allow querying locations by activity, most checkins, or most favorites (requires the CGSocialApp module).</li>
     <li>Code cleanups, and minor bug fixes.</li>
   </ul>
 </li>
 <li>1.19.x
   <ul>
     <li>Adds an Icon field type (from CGGoogleMaps or CGGoogleMaps2)</li>
     <li>Adds an Activity field type (from CGSocialApp)</li>
     <li>Adds the ability to re-order categories and hierarchy items.</li>
     <li>More code cleanups.</li>
     <li>Hierarchy optimizations.</li>
     <li>Adds the {cd_hierbreadcrumb} plugin.</li>
     <li>Adds the hier_children parameter.</li>
     <li>More indexes for preformance <em>(1.19.7)</em></li>
     <li>Improved Hierarchy List Template <em>(1.19.7)</em></li>
   </ul>
 </li>
 <li>1.20.x
   <ul>
     <li>Adds support for the name parameter in the category list action.</li>
     <li>Adds the ability to reorder field definitions.</li>
     <li>Removes old search action.
       <p><strong>Note:</strong>  Sites using CompanyDirectory search from prior to version 1.15 will need to re-create search templates.</p>
     </li>
     <li>Removes old fe_edit action.
       <p><strong>Note:</strong>  Sites using CompanyDirectory fe_edit from prior to version 1.15 will need to re-create fe_edit templates.</p>
     </li>
   </ul>
 </li>
 <li>1.21.x
   <ul>
     <li>Adds saved search functionality.</li>
     <li>Search fixes and improvements</li>
     <li>Adds full text searching (in boolean mode)</li>
     <li>Adds support for refining the search</li>
   </ul>
 </li>
  <li>1.22.x
    <p><span style="color: red;"><strong>Note:</strong> There will be backwards compatibility issues with this version.</span>  Particularly with the browsehier and categorylist actions.  You will need to revise your templates for these views (please reset the prototype templates and refer to them when re-styling your templates).</p>
    <p>Additionally, searching through child categories and child hierarchies is now enabled by default with the hier= and category= parameters, and can only be disabled with the nochildren parameter.</p>
    <p><strong>Details:</strong>
    <ul>
      <li>Adds nested categories.</li>
      <li>Adds the summarypage parameter for detail, categorylist and browsehier views.</li>
      <li>No longer delete hierarchies with children.</li>
      <li>Rewrite the categorylist action.</p>
      <li>Rewrite the browsehier action.</li>
      <li>No longer support the name parameter in categorylist action.</li>
      <li>No longer support the hier_children parameter.... see nochildren</li>
      <li>Adds simple pretty urls for hierarchy based summary views.</li>
      <li>categorylist and browsehier actions now support the nopretty stuff to entirely disable pretty URLS and allow compounding parameters.</li>
      <li>Rewrite ASCII export and import.
	<p><strong>Note:</strong> The import format is similar to, but no longer identical to the old one.  You may need to change your files.</p>
      </li>
      <li>Adds filtering, and entity decoding to frontend text and text area fields <em>(1.22.3)</em></li>
	<li>Adds the ability to disable the WYSIWYG entirely <em>(1.22.6)</em></li>)
	<li>Now require PHP 5.4.x <em>(1.22.9)</em></li>
      <li>Adds the ajax_autocomplete_categories action for use in various forms. (1.22.13)
          Also adds a new javascript class to work along side this (documentation is on the todo list)
      </li>
      <li>Minor cleanups to the search and fesubmit actions.</li>
    </ul>
  </li>

    <li>1.23.x
	<ul>
	<li>Adds the abclist action which provides an alphabetic directory (by company name) and a paginated summary view.</li>
	<li>Search module now indexes the hierarchy long name and category long name.</li>
        <li>Fix minor issue with filtering by name regex.</li>
	</ul>
    </li>
</ul>
