<ul>
	<li>
		<p><strong>1.0.1</strong> 23-12-2016</p>
		<p>Code fixes</p>
		<p>Fixes for PHP 7</p>
	</li>
	<li>
		<p><strong>1.0</strong> 16-9-2014</p>
		<p>Code fixes</p>
		<p>Fixes for Core 2.0 release</p>
		<p>FR#2222 - List All Quotes</p>
		<p>FR#5700 - Show Author and Group in the listing for each Quote</p>
		<p>Disabled RSS quotes support (for now)</p>
	</li>
	<li>
		<p><strong>0.1.2</strong></p>
		<p>Fixed strange little bug, potentially breaking qotd</p>
		<p>Removed a couple of debug echo's</p>
	</li>
	<li>
		<p><strong>0.1.1</strong></p>
		<p>Added RSS-quotes support. Not perfect, but it's there.</p>
		<p>Fixed a bug rendering deletion of quotes impossible</p>
	</li>
	<li><strong>0.1.0</strong> - initial release</li>
</ul>