<div id="page_tabs">
    <div id="general">General</div>
	<div id="start">Getting started</div>
	<!--<div id="troubleshooting">Troubleshooting</div>-->
	<div id="support">Support</div>
    <div id="copyright">Copyright and License</div>
</div>

<div class="clearb"></div>

<div id="page_content">
	<div id="general_c">
		<p>This module allows easy maintenance and insertion of quotes into your pages/templates.<br />
		The quotes can be attached to groups and several options for selection of quote to show is available.</p>
	</div>
	
	<div id="start_c">
		<p>Insert a module-call into your page or template like this:</p>
		<pre>{Quotes}</pre><br />
		<pre>{Quotes group='name,name2'}</pre><br />
		<pre>{Quotes number=3}</pre><br />
		<pre>{Quotes pickedby='day'}</pre><br />
		<pre>{Quotes showall='1'}</pre><br />
		<pre>{Quotes template='default'}</pre><br />
		<pre>{Quotes quote='some quote'}</pre>
	</div>
	
	<!--
	<div id="troubleshooting_c">
		<p>...</p>
	</div>
	-->
	
	<div id="support_c">
		<p>This module does not contain any commercial support. If you have problems, ask for help in the:</p>
		<ul>
			<li><a href="http://forum.cmsmadesimple.org/" target="_blank">CMS Made Simple forums</a>,</li>
			<li><a href="irc://irc.freenode.net/cms" target="_blank"><abbr title="Internet Relay Chat">IRC</abbr> chat</a>,</li>
			<li>or write an email to the author</li>
		</ul>
		<br />
	</div>
	
	<div id="copyright_c">
		<p>Copyright &copy; 2014, Morten Poulsen [morten at poulsen dot org]. All Rights Are Reserved.</p>
		<br />
		<p>This module has been released under the <a href="http://www.gnu.org/licenses/licenses.html#GPL" target="_blank">GNU Public License v3</a>.<br />
		However, as a special exception to the GPL, this software is distributed as an addon module to CMS Made Simple&trade;.<br />
		You may only use this software when there is a clear and obvious indication in the admin section that the site was built with <b>CMS Made Simple&trade;</b>.</p>
	</div>
</div>