<ul>
  <li>1.0.4 - October 2009
    <p>Adds json support.</p>
  </li>
  <li>1.0.5 - November 2009
    <p>Adds no_css and no_js options to the incjs action.</p>
  </li>
  <li>1.0.6 - April 2010
    <p>Adds calguys date utils plugin.</p>
  </li>
  <li>1.0.9 - September 2010
    <p>Adds no_jquery option to the incjs action.</p>
    <P>Do not output jquery tags for any module actions or admin actions if CMS Version is >= CMS 1.9-beta1</p>
  </li>
  <li>1.0.10 -
    <p>Minor fixes.</p>
  </li>
  <li>1.0.11 - June 2011
    <ul>
      <li>Minor Fixes.</li>
      <li>Moves Changelog External.</li>
      <li>Minor change for 1.10 compatibility.</li>
      <li>Update dependencies.</li>
    </ul>
  </li>
  <li>1.1 - July 2012
   <ul>
     <li>Move help external.</li>
     <li>Upgrade jquery and fancybox.</li>
   <ul>
  </li>
  <li>1.2 - January 2013
    <ul>
      <li>Adds the require and placemarker actions.</li>
      <li>Upgrades all libraries and reformats them into a different structure.</li>
      <li>Adds jquery ui,  and CDN support.</li>
    </ul>
  </li>
  <li>v1.3 - June 2014
      <ul>
        <li>Adds support for the cgjs_require stuff in CGExtensions.</li>
	<li>Adds a new combobox plugin.</li>
	<li>Adds jsviews plugin.</li>
      </ul>
    </ul>
  </li>
  <li>v1.3,5
      <ul>
        <li>Minor improvements.</li>
      </ul>
    </ul>
  </li>
  <li>v1.3.6
    <ul>
      <li>Now flag different minifications for different libraries (when using cgjs_render)</li>
      <li>Upgrade jquery to 1.11.3</li>
      <li>Upgrade jquery-ui to 1.11.4</li>
    </ul>
  </li>
  <li>v1.3.8
    <p>Minor bug fixes.</p>
  </li>
  <li>v1.3.9
    <ul>
      <li>Upgrade the jquery file upload library.</li>
    </ul>
  </li>
</ul>
