<ul>
	<li>version 1.0 - initial version sent to client.</li>
	<li>version 1.0.1
	<ul>
	        <li>Adds support for noattrs tags like &lt;title&gt;</li>
		<li>Adds changelog.</li>
	</ul>
	<li>version 1.0.5
	<ul>
	        <li>Adds the {cghm_config_set} smarty plugin.</li>
		<li>Change the default prototype for various description fields.</li>
	</ul>
	<li>version 1.0.6
	<ul>
	  <li>changes &quot;shortcut-icon&quot; field to &quot;shortcut icon&quot;</li>
	  <li>Adds the ability to tell if a specific attribute should represent an existing file.</li>
	  <li>Improvements for default value calculation.</li>
	</ul>
	</li>
	<li>version 1.0.7
	<ul>
	  <li>Fixes for the meta author and publisher tag vs. the link author and publisher tags.</li>
	  <li>Fixes for defaults for multi-attribute tags.</li>
	</ul>
	</li>
	<li>version 1.0.8
	<ul>
 	  <li>Adds image_src tag.</li>
	  <li>Fixes open graph stuff.</li>
	  <li>Change default template for a bunch of tags.</li>
	</ul>
	</li>
	<li>version 1.0.9
	<ul>
 	  <li>Minor fixes to the fields.ini</li>
	  <li>Updates help.</li>
	</ul>
	</li>

	<li>version 1.0.14
	<ul>
 	  <li>Adds twitter title tag.</li>
	  <li>Revert template changes for title wrt. sitename.</li>
	</ul>
	</li>
</ul>
