<h3>About</h3>

<p>This module gathers data in support of the SimpleSiteMgr module.<br />
An automaticly generated Pass Phrase is used to encrypt the version info data.</p>

<h3>Usage</h3>

<p>There is only one item that can be changed, the "Pass Phrase" used to encrypt the version info file. 
When you open the Admin panel for this module, you can click the button to recreate a new password, which is stored in the siteprefs table.</p>

<p><b>NOTE:</b> You must use the same "Pass Phrase" in the SimpleSiteMgr module entry for this site, or you will not be able to decrypt the version data.</p>

<h3>Debug mode</h3>

<p>When you enable debug in the CMSMS config.php file, the SimpleSiteInfo module has a few built in checks that will help you troubleshoot when SimpleSiteMgr can't read the website's data. The SimpleSiteInfo module page will tell you more in debug mode!</p>

<h3>Support</h3>

<p>This module does not contain any commercial support. If you have problems, ask for help in the:</p>
<ul>
	<li><a href="http://forum.cmsmadesimple.org/" target="_blank">CMS Made Simple forums</a>,</li>
	<li><a href="irc://irc.freenode.net/cms" target="_blank"><abbr title="Internet Relay Chat">IRC</abbr> chat</a>,</li>
	<li>or write an email to the author</li>
</ul>

<h3>Copyright</h3>

<p>Copyright &copy; 2008-2017, Noel McGran [nmcgran at telus dot net], Rolf Tjassens [info at cmscanbesimple dot org]. All Rights Are Reserved.</p>
<br />
<p>This module has been released under the <a href="http://www.gnu.org/licenses/licenses.html#GPL" target="_blank">GNU Public License v3</a>.<br />
However, as a special exception to the GPL, this software is distributed as an addon module to CMS Made Simple&trade;.<br />
You may only use this software when there is a clear and obvious indication in the admin section that the site was built with <b>CMS Made Simple&trade;</b>.</p>

<br />