<?php
$lang['help_group_permissions'] = '<h4>Berechtigungsmodell für Administrationsbenutzer</h4>
<p>CMS Made Simple (CMSMS) verwendet ein System von namentlichen Berechtigungen. Diese Berechtigungen bestimmen die Fähigkeit eines Benutzers, verschiedene Funktionen im Administrationsbereich von CMSMS auszuführen. Die Grundversion von CMSMS erstellt mehrere Berechtigungen während der Installation – gelegentlich werden während einer Aktualisierung Berechtigungen hinzugefügt oder gelöscht. Module von Drittanbietern können zusätzliche Berechtigungen erstellen.</p>
<p>Berechtigungen werden Benutzergruppen zugeordnet. Ein autorisierter Benutzer kann die Berechtigungen, die bestimmten Mitgliedergruppen zugeordnet sind, anpassen. Die Benutzergruppe „Admin“ ist eine spezielle Gruppe; Mitglieder dieser Gruppe haben automatisch alle Berechtigungen. Admin-Benutzerkonten können Mitglieder von null oder mehr Gruppen sein.</p>
<p>Es kann für ein Benutzerkonto, das nicht ein Mitglied einer Gruppe ist, dennoch möglich sein, verschiedene Funktionen auszuführen; mehr Informationen über Eigentumsrechte und zusätzliche Redakteure gibt es in der Dokumentation von Inhaltsverwaltung und Designverwaltung. Das erste Benutzerkonto <em> (uid=1)</em>, welches in der Regel mit den Namen „Admin“ trägt, ist ein spezielles Benutzerkonto und hat alle Berechtigungen.</p>';
$lang['help_myaccount_admintheme'] = 'Design der Benutzeroberfläche des Administrationsbereichs auswählen. Verschiedene Designs können unterschiedliche Layouts, Menüstrukturen oder sonstige Funktionen vorweisen.';
$lang['help_myaccount_email'] = 'Geben Sie hier eine E-Mail-Adresse an, die für vergessene Kennwörter und für Benachrichtigungen des Systems oder von sonstigen Modulen verwendet wird.';
$lang['help_myaccount_firstname'] = 'Geben Sie hier optional ihren Vornamen an; dieser kann in der Administration verwendet werden, oder um E-Mails an Sie zu personalisieren.';
$lang['help_myaccount_hidehelp'] = 'Ist diese Option aktiviert, wird das System Verweise zur Modulhilfe im Administrationsbereich verstecken. In den meisten Fällen ist die Hilfe, die von Modulen bereitgestellt wird, für Entwickler von Webseiten vorgesehen und möglicherweise nicht wirklich nützlich für Bearbeiter von Inhalten.';
$lang['help_myaccount_homepage'] = 'Sie können eine Seite im Administrationsbereich auswählen, auf der Sie direkt landen, wenn Sie sich im hier anmelden. Dies kann nützlich sein, wenn sie hauptsächlich eine bestimmte Funktion auf einer bestimmten Seite nutzen.';
$lang['help_myaccount_ignoremodules'] = 'Wenn Administrationsbenachrichtigungen aktiviert sind, können Sie hier wählen, Benachrichtigungen von bestimmten Modulen zu ignorieren';
$lang['help_myaccount_indent'] = 'Diese Option gibt der Inhaltsauflistung Einrückungen, um über- und untergeordnete Seitenbeziehungen zu verdeutlichen.';
$lang['help_myaccount_language'] = 'Hier kann die Sprache ausgewählt werden, in der die Administrationsoberfläche angezeigt wird; die Liste der verfügbaren Sprachen kann in unterschiedlichen CMS-Installationen variieren, je nachdem welche Sprachpakete installiert sind.';
$lang['help_myaccount_lastname'] = 'Geben Sie hier optional ihren Nachnamen an; dieser kann in der Administration verwendet werden, oder um E-Mails an Sie zu personalisieren.';
$lang['help_myaccount_password'] = 'Bitte geben Sie ein einzigartiges und sicheres Kennwort für die Website an; das Kennwort sollte mehr als sechs Zeichen lang sein und eine Kombination aus Groß- und Kleinbuchstaben, Zahlen und Sonderzeichen sein. Wenn sie das Kennwort nicht ändern wollen, lassen sie das Feld einfach leer.';
$lang['help_myaccount_passwordagain'] = 'Um Fehler zu vermeiden, geben Sie das Kennwort bitte nochmal an; wenn sie das Kennwort nicht ändern wollen, lassen sie das Feld einfach leer.';
$lang['help_myaccount_syntax'] = 'Wählen Sie ein Modul aus, das Syntaxhervorhebung beim Bearbeiten von Code ermöglicht; die Liste der verfügbaren Module kann variieren und ist abhängig von der Konfiguration des Webseitenadministrators.';
$lang['help_myaccount_username'] = 'Ihr Benutzername ist Ihr einzigartiger Name für den Administrationsbereich; bitte nur alphanumerische Zeichen und ggfs. Unterstrich verwenden.';
$lang['help_myaccount_wysiwyg'] = 'Wählen sie aus, welchen <a href="https://de.wikipedia.org/wiki/WYSIWYG" rel="external"><abbr title="„What You See Is What You Get“">WYSIWYG</abbr></a>-Editor sie während der Inhaltsbearbeitung verwenden wollen. Sie können auch „Kein(e)/ohne Vorgabe“ auswählen, wenn sie mit dem Schreiben von HTML-Code vertraut sind; die Liste der verfügbaren Module kann variieren und ist abhängig von der Konfiguration des Webseitenadministrators.';
$lang['settings_adminlog_lifetime'] = 'Diese Einstellung gibt die maximale Zeitspanne an, für die Einträge im Administrationslogbuch behalten werden.';
$lang['settings_autoclearcache'] = 'Die Option ermöglicht die Angabe eines Maximalzeitraums (in Tagen), nach dem Dateien aus dem Zwischenspeicher gelöscht werden. Diese Angabe ist nützlich, um sicherzustellen, dass zwischengespeicherte Dateien regelmäßig neu generiert werden und dass das System nicht mit alten, unnötigen Dateien überladen wird. Empfohlen werden Werte zwischen 14 und 30 Tagen; der Zwischenspeicher wird aber höchtens ein Mal pro Tag geleert.';
$lang['settings_checkversion'] = 'Ist dies aktiviert, prüft das System täglich, ob eine neue Version von CMS Made Simple verfügbar ist.';
$lang['settings_mailtest_testaddress'] = 'Geben Sie eine gültige E-Mail-Adresse an, an die die Test-E-Mail gesendet wird.';
?>