<?php
$lang['help_group_permissions'] = '<h4>CMSMS Admin Tillatelse Modell</h4>
<ul>
<li>CMSMS bruker et system av navngitte rettigheter. Tilgang til disse tillatelsene bestemmer en brukers evne til å utføre forskjellige funksjoner i CMSMS administrasjonskonsollen .</li>
<li>CMSMS kjernen skaper flere tillatelser på installasjon <em>(tidvis tillatelser legges til eller slettes under en oppgraderingsprosessen)</em>.  Tredjeparts moduler kan skape ytterligere tillatelser.</li>
<li>Tillatelser er forbundet med brukergrupper.  En autorisert bruker kan justere tillatelsene som er forbundet med visse medlemsgrupper <em>(Inkludert tilgang til å endre en gruppe tillatelser)</em>.<strong>Admin</strong> gruppen er en spesiell gruppe. Medlemmer av denne gruppen vil ha alle tillatelser.</li>
<li>Admin brukerkontoer kan være medlemmer av ingen eller flere grupper. Det kan være mulig for en brukerkonto som ikke er medlem av noen grupper å fortsatt utføre ulike funksjoner<em>(Les om eierskap og ekstra-redaktører i Content Manager hjelp, og design hjelp Manager).</em>.  Den første brukerkontoen <em>(uid == 1)</em>, som vanligvis er navngitt "Admin" er en spesiell brukerkonto og vil ha alle tillatelser.</li>
</ul>';
$lang['help_myaccount_admincallout'] = 'Hvis aktivert administrative bokmerker <em>(shortcuts)</em> vil bli aktivert slik at du kan administrere en liste over ofte brukte handlinger i administrasjonskonsollen .';
$lang['help_myaccount_admintheme'] = 'Velg et administrasjons tema å bruke. Ulike administrasjons temaer har forskjellige menyoppsett, fungerer bedre for mobile skjermer, og har ulike tilleggsfunksjoner .';
$lang['help_myaccount_ce_navdisplay'] = 'Velg hvilke innholdsfeltet skal vises i innholdslister. Alternativene inkluderer sidetittelen , eller menytekst . Hvis " Ingen" er valgt, så området preferanse vil bli brukt';
$lang['help_myaccount_dateformat'] = 'Angi et datoformat streng å bruke når datoer vises. Denne strengen bruker <a href="http://php.net/manual/en/function.strftime.php" class="external" target="_blank">strftime</a> format.  <strong>Merk:</strong> noen tredjeparts add-ons kan ikke adlyde denne innstillingen.</strong>';
$lang['help_myaccount_dfltparent'] = 'Angi standard siden for å opprette en ny innholdsside . Bruken av denne innstillingen avhenger også på innholdsredigeringstillatelser.<br/><br/>Bor ned til den valgte standard ordnede siden ved å velge den øverste overordnede , og påfølgende ordnede sider fra den medfølgende rullegardinlistene .<br/><br/>Tekstfeltet til høyre vil alltid indikere hvilken side som er valgt.';
$lang['help_myaccount_email'] = 'Angi en e-postadresse. Dette brukes for glemt passord funksjonalitet, og for noen typer e-post sendt av systemet (eller tilleggs moduler).';
$lang['help_myaccount_enablenotifications'] = 'Hvis aktivert, vil systemet vise ulike meldinger om ting som må tas vare på i navigasjon';
$lang['help_myaccount_firstname'] = 'Eventuelt oppgi fornavn. Dette kan brukes i Admin tema, eller å personlig håndtere e-post til deg';
$lang['help_myaccount_hidehelp'] = 'Hvis dette er aktivert vil systemet skjule modul hjelpe lenker fra administrasjonskonsollen . I de fleste tilfeller for å gi hjelp med moduler er rettet mot nettstedet utviklere og kan ikke være nyttig for innhold redaktører.';
$lang['help_myaccount_homepage'] = 'Du kan velge en side som du laster automatisk til når du logger på CMSMS administrasjonskonsollen . Dette kan være nyttig når du primært bruker en funksjon.';
$lang['help_myaccount_ignoremodules'] = 'Hvis Admin varslinger er aktivert kan du velge å ignorere meldinger fra enkelte moduler';
$lang['help_myaccount_indent'] = 'Dette alternativet vil rykke innholdet listevisning  for å illustrere den overordnedes  og underordnedes siden forhold';
$lang['help_myaccount_language'] = 'Velg språket som skal vises for Admin grensesnittet. Listen over tilgjengelige språk kan variere på hver CMSMS installere';
$lang['help_myaccount_lastname'] = 'Eventuelt spesifisere ditt etternavn. Dette kan brukes i Admin tema, eller å personlig håndtere e-post til deg';
$lang['help_myaccount_password'] = 'Skriv inn et unikt, og sikkert passord for dette nettstedet. Passordet bør være mer mer enn seks tegn, og bør bruke en kombinasjon av store bokstaver, små bokstaver, ikke alfanumerisk , og sifre. Vennligst la dette feltet stå tomt hvis du gjør noe som ikke trenger passord endring.';
$lang['help_myaccount_passwordagain'] = 'For å redusere feil, må du skrive inn passordet ditt på nytt. La dette feltet stå tomt hvis du ikke ønsker å endre passordet.';
$lang['help_myaccount_syntax'] = 'Velg hvilke syntax highlighting modul for å bruke når du redigerer HTML, eller Smarty kode. Listen over tilgjengelige moduler kan endres avhengig av hva nettstedet administratoren har konfigurert';
$lang['help_myaccount_username'] = 'Brukernavnet ditt er unikt navn på CMSMS Admin panelet. Bruk bare alfanumeriske tegn og understrek';
$lang['help_myaccount_wysiwyg'] = 'Velg hvilken WYSIWYG <em>(Det du ser er hva du får)</em> Modul som skal brukes når du redigerer HTML-innhold. Du kan også velge "None"Hvis du er komfortabel med html. Listen over tilgjengelige WYSIWYG-redaktører kan endres avhengig av hva nettstedet administrator har konfigurert.';
$lang['settings_adminlog_lifetime'] = 'Denne innstillingen angir maksimumstiden som oppføringer i Admin loggen bør beholdes.';
$lang['settings_autoclearcache'] = 'Dette alternativet lar deg angi maksimal alder <em>(I dager)</em> Før filer i buffer mappen blir slettet.<br/><br/>Dette alternativet er nyttig for å sikre at arkiverte filer regenereres periodisk, og at filsystemet ikke blir forurenset av gamle og unødvendige filer. En ideell verdi for dette feltet er 14 eller 30 dager.<br /><br /><strong>Merk:</strong>Cached filer blir ryddet maksimalt en gang per dag.';
$lang['settings_autocreate_flaturls'] = 'Hvis SEF/vakre nettadresser er aktivert, og alternativet for å opprette nettadresser er aktivert, angir dette alternativet at de automatisk opprettede nettadressene skal være flate <em>(i.e: Identisk med sidens alias)</em>.  <strong>Merk:</strong> De to verdiene trenger ikke å forbli identiske, URL-verdien kan endres for å være annerledes enn sidens alias i senere sidedigeringer';
$lang['settings_autocreate_url'] = 'Når du redigerer innholdssider , bør SEF / pen webadresser bli automatisk laget? Auto skape webadresser vil ikke ha noen effekt dersom pene webadresser ikke er aktivert i CMSMS config.php filen.';
$lang['settings_badtypes'] = 'Velg hvilke innholdstyper du vil fjerne fra rullegardinmenyen for innholdstype når du redigerer eller legger til innhold. Denne funksjonen er nyttig hvis du ikke vil at redaktører skal kunne lage bestemte typer innhold.  Bruk CTRL + Klikk for å velge, avmarkere elementer. Å ha ingen utvalgte elementer vil indikere at alle innholdstyper er tillatt. <em>(gjelder for alle brukere)</em>';
$lang['settings_basicattribs2'] = 'Dette feltet lar deg spesifisere hvilke innholdsegenskaper som brukere uten "administrer alt innhold" tillatelse kan endres.<br />Denne funksjonen er nyttig når du har innholdsredaktører med begrenset tillatelse og vil tillate redigering av ytterligere innholdsegenskaper.';
$lang['settings_browsercache'] = 'Gjelder bare å bufres sider, indikerer denne innstillingen at nettlesere skal få lov til å bufres sidene for en tidsperiode. Hvis aktivert gjenta besøkende til nettstedet ditt, kan ikke umiddelbart se endringer i innholdet på sidene, men å aktivere dette alternativet kan alvorlig forbedre ytelsen til nettstedet ditt.';
$lang['settings_browsercache_expiry'] = 'Angi hvor lang tid (i minutter) som nettlesere bør bufre sider for. Konfigurere denne verdien til Verdien 0 skrur av funksjonaliteten. I de fleste tilfeller bør du angi en verdi som er større enn 30';
$lang['settings_checkversion'] = 'Hvis aktivert, vil systemet utføre en daglig sjekk for en ny utgave av CMSMS';
$lang['settings_contentimage_path'] = 'Denne innstillingen brukes når en sidemal inneholder {content_image} stikkord.  Den katalogen som er spesifisert her, brukes til å gi et utvalg av bilder som skal knyttes til stikkordet.<br /><br />I forhold til opplastingsbanen, angi et katalognavn som inneholder stiene som inneholder filer for {content_image} stikkord. Denne verdien brukes som standard for dir-parameteren';
$lang['settings_disablesafemodewarn'] = 'Dette alternativet deaktiverer en advarsel hvis CMSMS oppdager det <a href="https://php.net/manual/en/features.safe-mode.php" class="external" target="_blank">PHP Sikker Modus</a> har blitt oppdaget.<br /><br /><strong>Note:</strong> Sikker modus har blitt avviklet fra PHP 5.3.0 og fjernet for PHP 5.4.0. CMSMS støtter ikke operasjonen i sikker modus, og vårt supportteam gir ingen teknisk assistanse for installasjoner der sikker modus er aktiv';
$lang['settings_enablenotifications'] = 'Dette alternativet vil aktivere varsler blir vist øverst på siden i hvert Admin forespørsel. Dette er nyttig for viktige varsler om system som kan kreve handling fra brukeren. Det er mulig for hver Admin bruker å slå av varsler i sine preferanser.';
$lang['settings_enablesitedown'] = 'Dette alternativet lar deg veksle nettstedet er "nede for vedlikehold" for nettstedet besøkende';
$lang['settings_enablewysiwyg'] = 'Aktiver WYSIWYG-editor i tekstområdet nedenfor';
$lang['settings_imagefield_path'] = 'Denne innstillingen brukes når du redigerer innhold. Den katalogen som er spesifisert her, brukes til å gi en liste over bilder hvorfra du skal knytte et bilde til innholdssiden.<br/></br/>I forhold til bildeopplastings-banen, angi et katalognavn som inneholder stiene som inneholder filer for bildefeltet';
$lang['settings_lock_timeout'] = 'Skriv inn en standardverdi (i minutter) for låser til tidsavbrudd. Denne brukes hvis et stykke av funksjonalitet ikke gir en tilpasset lås tidsavbrudd verdi';
$lang['settings_mailprefs_from'] = 'Dette alternativet styrer <em>standard<em> adresse som CMSMS vil bruke til å sende e-postmeldinger. Dette kan ikke bare være en e-postadresse. Den må samsvare med det domenet CMSMS leverer. Angi en personlig e-postadresse fra et annet domene er kjent som "<a href="https://en.wikipedia.org/wiki/Open_mail_relay" class="external" target="_blank">relaying</a>" og vil trolig føre til at e-post ikke sendes, eller ikke mottas av mottakerens e-postserver. Et typisk godt eksempel på dette feltet er noreply@mydomain.com';
$lang['settings_mailprefs_fromuser'] = 'Her kan du angi et navn for å bli assosiert med den e-postadressen som er angitt ovenfor. Dette navnet kan være hva som helst, men det er rimelig samsvarer med e-postadressen. dvs: " Ikke svar"';
$lang['settings_mailprefs_mailer'] = 'Dette valget styrer hvordan CMSMS vil sende e-post. Bruk PHPs postfunksjon, sendmail, eller ved å kommunisere direkte med en SMTP-server.<br/><br/>Det "mail" alternativet skal fungere på de fleste delte verter, men det nesten helt sikkert ikke vil fungere på de fleste selv vert Windows-installasjoner.<br/><br/>Det "sendmail" alternativet bør fungere på de fleste riktig konfigurert selvbetjente Linux-servere. Det kan imidlertid ikke fungere på delte verter.<br/><br/>SMTP-alternativet krever konfigurasjonsinformasjon fra verten din.';
$lang['settings_mailprefs_sendmail'] = 'Hvis du bruker"sendmail" mailer-metoden, må du angi hele banen til sendmail-binærprogrammet. En typisk verdi for dette feltet er "/usr/sbin/sendmail".  Dette alternativet brukes vanligvis ikke på Windows-verter.<br/><br/><strong>Merk:</strong> Hvis du bruker dette valget, må verten tillate popen og pclose PHP-funksjonene som ofte er deaktivert på delte verter.';
$lang['settings_mailprefs_smtpauth'] = 'Når du bruker SMTP-maileren, indikerer dette alternativet at SMTP-serveren krever godkjenning for å sende e-post. Du må da spesifisere <em>(på et minimum)</em> et brukernavn og passord. Verten din bør angi om SMTP-godkjenning er nødvendig, og hvis så gi deg et brukernavn og passord, og eventuelt en krypteringsmetode.<br/><br/><strong>Merk:</strong> SMTP-godkjenning kreves dersom domenet ditt bruker Google-apper for e-post.';
$lang['settings_mailprefs_smtphost'] = 'Når du bruker SMTP mailer, dette alternativet Spesifisere vertsnavnet <em>(eller IP-adresse)</em> på SMTP-serveren til å brukes når du sender e-post. Du trenger å kontakte din vert for riktig verdi.';
$lang['settings_mailprefs_smtppassword'] = 'Dette er passordet for tilkobling til SMTP-serveren hvis SMTP-autentisering er aktivert.';
$lang['settings_mailprefs_smtpport'] = 'Når du bruker SMTP mailer dette alternativet angir heltall portnummer for SMTP-serveren. I de fleste tilfeller denne verdien er 25, selv om du kanskje må kontakte din vert for riktig verdi.';
$lang['settings_mailprefs_smtpsecure'] = 'Dette alternativet, når du bruker SMTP-autentisering angir en krypteringsmekanisme til bruk ved kommunikasjon med SMTP-serveren. Verten din bør gi denne informasjonen hvis SMTP-autentisering er nødvendig.';
$lang['settings_mailprefs_smtptimeout'] = 'Når du bruker SMTP-maileren, angir dette alternativet antall sekunder før et forsøk på tilkobling til SMTP-serveren vil mislykkes. En typisk verdi for denne innstillingen er 60.<br/><br/><strong>Merk:</strong> Hvis du trenger en lengre verdi her, indikerer det sannsynligvis et underliggende DNS-, rutingen eller brannmurproblem, og du må kanskje kontakte verten din.';
$lang['settings_mailprefs_smtpusername'] = 'Dette er brukernavnet for å koble til SMTP-serveren hvis SMTP-autentisering er aktivert.';
$lang['settings_mailtest_testaddress'] = 'Angi en gyldig e-postadresse som skal motta test epost';
$lang['settings_mandatory_urls'] = 'Hvis SEF/pene URLer er aktivert, angir dette alternativet om side urls er et obligatorisk felt i innholdet editor.';
$lang['settings_nosefurl'] = 'For å konfigurere <strong>H</strong>ver <strong>M</strong>otor <strong>V</strong>ennlig <em>(pene)</em> URL-er Må du redigere noen linjer i config.php filen din og muligens redigere en .htaccess-fil eller konfigurasjonen av webservere.   Du kan lese mer om hvordan du konfigurerer pene urls <a href="https://docs.cmsmadesimple.org/configuration/pretty-url" class="external" target="blank"><u>her</u></a> »';
$lang['settings_pseudocron_granularity'] = 'Denne innstillingen angir hvor ofte systemet vil forsøke å håndtere regelmessig planlagte oppgaver.';
$lang['settings_searchmodule'] = 'Velg modul som skal brukes til å indeksere ord for å søke, og vil gi stedet søkefunksjoner';
$lang['settings_sitedownexcludeadmins'] = 'Må vise nettsiden til Administrator brukere innlogget til CMSMS administrasjonskonsollen';
$lang['settings_sitedownexcludes'] = 'Må vise nettsiden til disse IP-adressene';
$lang['settings_sitedownmessage'] = 'Meldingen til din nettside, når nettsiden er nede for vedlikehold';
$lang['settings_smartycaching'] = 'Når den er aktivert, vil produksjonen fra forskjellige plugins bli lagret for å øke ytelsen. I tillegg blir de fleste porsjonene av kompilerte maler bufret. Dette gjelder bare utdata på innholdssider merket som cachable, og bare for brukere uten administrasjon. Merk, denne funksjonaliteten kan forstyrre oppførselen til enkelte moduler eller plugins, eller plugins som bruker ikke-inline-skjemaer.<br/><br/><strong>Merk:</strong> Når Smarty caching er aktivert, globale innholdsblokker <em>(GCBs)</em> Er alltid cached av smarty og brukerdefinerte koder <em>(UDTs)</em>Blir aldri bufret. I tillegg blir innholdsblokkene aldri bufret.';
$lang['settings_smartycompilecheck'] = 'Hvis deaktivert, vil Smarty ikke sjekke modifikasjons datoene for maler for å se om de har blitt endret. Dette kan forbedre ytelsen. Men utfører noen mal endring (eller enda noen endringer i innholdet) kan kreve en buffer rensing';
$lang['settings_thumbfield_path'] = 'Denne innstillingen brukes når du redigerer innhold. Katalogen er angitt her brukes til å gi en liste over bilder for å knytte et miniatyrbilde med innholdssiden.<br/><br/>I forhold til bildeopplastingsbanen, angi et katalognavn som inneholder stiene som inneholder filer for bildefeltet. Vanligvis vil dette være det samme som banen ovenfor.';
$lang['settings_umask'] = 'Den &quot umask" er en octal verdi som brukes til å angi standard tillatelse til nyopprettede filer (dette er brukt for filer i cache katalogen, og opplastede filer For mer informasjon se riktig <a href = "http://en.wikipedia.org/wiki/Umask" class="external" target="_blank">Wikipedia artikkel.</a>';
$lang['siteprefs_lockrefresh'] = 'Dette feltet angir minimumsfrekvensen (i minutter) Ajax basert låsemekanismen skal "kontakt" en lås. En ideell verdi for dette feltet er fem.';
$lang['siteprefs_locktimeout'] = 'Dette feltet angir antall minutter med inaktivitet før en lås blir tidsavbrutt. Etter en lås blir tidsavbrutt, kan andre brukere stjele låsen. For at en lås ikke skal bli tidsavbrutt, må den være "rørt"  før utløps tid. Dette tilbakestiller utløpstid av låsen. I de fleste tilfeller bør en 60 minutters lås være egnet.';
$lang['siteprefs_sitename'] = 'Dette er et lesbart navn på ditt nettsted, i.s: bedrift, klubb, eller organisasjonsnavn';
$lang['siteprefs_frontendlang'] = 'Standardspråket nettstedet ditt viser på frontend. Dette kan endres på en per-side basis ved hjelp av ulike Smarty koder. dvs: <code>{cms_set_language}</code>';
$lang['siteprefs_frontendwysiwyg'] = 'Når WYSIWYG redaktør, er gitt på frontend former, bør hva WYSIWYG modulen brukes? Eller ingen.';
$lang['siteprefs_nogcbwysiwyg'] = 'Dette alternativet vil deaktivere WYSIWYG redaktør på alle globale innholdsblokker uavhengig av brukerinnstillinger , eller for de enkelte globale innholdsblokker';
$lang['siteprefs_globalmetadata'] = 'Dette tekst området gir mulighet til å legge inn metainformasjon som er relevant for alle innholdssider. Dette er et ideelt sted for metakoder som Generator, og forfatter, etc.';
$lang['siteprefs_logintheme'] = 'Velg Admin temaet (fra installerte Admin temaer) som skal brukes til å generere administrator login form, og som standard login tema for nye Admin brukerkontoer . Admin-brukere vil være i stand til å velge deres foretrukne Admin tema fra i brukerinnstillingene panel.';
$lang['siteprefs_backendwysiwyg'] = 'Velg WYSIWYG-editor for nyopprettede Admin brukerkontoer . Admin-brukere vil være i stand til å velge sin foretrukne WYSIWYG-editor fra i brukerens valgpanelet.';
$lang['siteprefs_dateformat'] = '<p>Angi datoformatstrengen i <a href="http://ca2.php.net/manual/en/function.strftime.php" class="external" target="_blank"><u>PHP strftime</u></a> Format som vil bli brukt <em>(som standard)</em> for å vise dato og klokkeslett på nettstedet ditt.</p><p>Admin-brukere kan justere disse innstillingene i brukerinnstillingspanelet.</p><p><strong>Merk:</strong> Noen moduler kan velge å vise tider og datoer annerledes</p>';
$lang['siteprefs_thumbwidth'] = 'Angi en bredde <em>(in pixels)</em> som skal brukes som standard når du genererer miniatyrbilder fra opplastede bildefiler. Miniatyrbilder vises vanligvis i administrasjons-panelet i FileManager-modulen eller når du velger et bilde som skal settes inn i sideinnhold. Noen moduler kan imidlertid bruke miniatyrbildene på nettsidenes frontend.<br/><br/><strong>Merk:</strong> Enkelte moduler kan ha flere innstillinger for hvordan du genererer miniatyrbilder, og ignorer denne innstillingen.';
$lang['siteprefs_thumbheight'] = 'Angi en høyde <em>(in pixels)</em>som skal brukes som standard når du genererer miniatyrbilder fra opplastede bildefiler.  Thumbnails er vanligvis vises i administrasjonspanelet i Filemanager modulen eller når du velger et bilde for å sette inn sideinnhold.  Imidlertidig kan noen moduler bruke miniatyrbildene på nettsidens frontend.<br/><br/><strong>Merk:</strong> Noen moduler kan ha flere preferanser for hvordan å generere miniatyrbilder , og ignorere denne innstillingen.';
?>