<ul>
  <li>Version 0.98 - Initial release</li>
  <li>Version 0.98.1 - Fixes</li>
  <li>Version 0.98.2 - Fixes</li>
  <li>Version 0.98.3 - Fixes</li>
  <li>Version 0.98.4 - Fixes</li>
  <li>Version 0.98.5 - Fixes</li>
  <li>Version 0.99 - More fixes</li>
  <li>Version 0.99.1
    <ul>
      <li>Documentation improvements.</li>
      <li>new features to the jquery plugin.</li>
      <li>bug fixes.</li>
      <li>Now Requires PHP 5.4.3+</li>
    </ul>
  </li>
  <li>Version 0.99.3
    <ul>
      <li>Minor bug fixes.</li>
    </ul>
  </li>
  <li>Version 1.1
    <ul>
	<li>Now requires an API key.
	   <p><strong>Note:</strong> If you are an existing user of CGGoogleMaps2 you will need to reset your map templates as an API key is required in the google maps URL where it previously was not.</p>
	</li>
    </ul>
  </li>
</ul>
